name: "Publish Release"
on:
  push:
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ GITHUB_SHA }}
        release_name: "${{ GITHUB_SHA }}"
        draft: true
        prerelease: false
    - name: Generate ZIP
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'withSubmodules.zip'
        exclusions: '*.git* *.github/workflows'
    - name: Add ZIP to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: withSubmodules.zip
        asset_name: withsubmodules.zip
        asset_content_type: application/zip
    - name: Generate TAR
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'tar'
        filename: 'withSubmodules.tar.gz'
        exclusions: '*.git* *.github/workflows'
    - name: Add TAR to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: withSubmodules.tar.gz
        asset_name: withsubmodules.tar.gz
        asset_content_type: application/gzip
    - name: Publish Release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}